### ISSUE TITLE
Unable to change all the variables at once

### ISSUE THREAD

**Issue by RahulRudra81** [RahulRudra81/WeatherMonitoring#1]
I have created function replaceVal in which I am trying to change the values of 5 variables in html file but I when i am returning the function it is able to return the changes in the last variable only. 

![image](https://user-images.githubusercontent.com/91683510/220277761-9802947f-d3ed-4436-8fad-433659a1a83f.png)

![image](https://user-images.githubusercontent.com/91683510/220277880-ee8f6457-21b9-42e2-9e6a-720395197a77.png)

![image](https://user-images.githubusercontent.com/91683510/220277981-867e830a-c1a4-44ff-9df7-e00f66d67f7a.png)

**Comment by the-marolie** [comment]
```
const replaceVal = (tempVal, orgVal) => {
    return tempVal.replace("{%tempval%}", orgVal.main.temp)
    .replace("{%tempmin%}", orgVal.main.temp_min)
    .replace("{%tempmax%}", orgVal.main.temp_max)
    .replace("{%location%}", orgVal.name)
    .replace("{%country%}", orgVal.sys.country)
};
```

Use this

**Comment by RahulRudra81** [comment]
Thanks . it worked
